remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Cuisine of a Lifetime
description: [The way that we percieve ood, is the way that we percieve life.]
