# AnotherFoodieblog
A blog about cuisines in general and from a stan point of a foodie.
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
