remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Cuisine of a Lifetime
description: [Food is but a God and I am nothing more than's it's humble servant.]
# The Cuisine of A Lifetime
## Another Foodie Blog



A blog about cuisines in general and from a stan point of a foodie.

I like to eat just as much as the next person, but also enjoy the experience that comes with it. I may not be a cook, but you do not need to be an executive chef to tell if a meal is delicious enough. Joy is a part of life, and for my fellow people who get a lot of it from food, let's traverse together through the delectible delights of this ever so fascinating menu of the world.

>https://live.staticflickr.com/2759/4385732951_fd0542c2cf_b.jpg 

## All About The Experience

